spring.application.name=demo

spring.datasource.url=jdbc:mysql://javaapplication-db.cjgy4m0eovet.ap-south-2.rds.amazonaws.com:3306/javaapplication-db

spring.datasource.username=admin

spring.datasource.password=Saikumar123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
